"""Email OTP delivery and verification for registration and login flows.

The default store is process-local memory. This is suitable for one local
process, but a shared cache such as Redis should be used before running more
than one Railway worker so every worker can verify codes generated by another.
"""

from __future__ import annotations

import hashlib
import hmac
import os
import re
import secrets
import smtplib
import ssl
import threading
import time
from dataclasses import dataclass
from email.message import EmailMessage
from html import escape


OTP_LENGTH = 6
OTP_TTL_SECONDS = 5 * 60
MAX_ATTEMPTS = 3
DEFAULT_SEND_COOLDOWN_SECONDS = 60
EMAIL_PATTERN = re.compile(r"^[^\s@]+@[^\s@]+\.[^\s@]+$")


class OTPError(RuntimeError):
    """Base class for expected OTP failures."""


class OTPConfigurationError(OTPError):
    """Raised when SMTP configuration is missing or invalid."""


class OTPDeliveryError(OTPError):
    """Raised when the SMTP server cannot accept the OTP message."""


class OTPRateLimitError(OTPError):
    """Raised when a recipient requests OTPs too frequently."""


@dataclass
class _OTPRecord:
    digest: bytes
    expires_at: float
    attempts: int = 0
    last_sent_at: float = 0.0


_records: dict[str, _OTPRecord] = {}
_records_lock = threading.RLock()


def _normalize_email(email: str) -> str:
    normalized = str(email or "").strip().lower()
    if not EMAIL_PATTERN.fullmatch(normalized) or len(normalized) > 320:
        raise ValueError("A valid email address is required.")
    return normalized


def _secret() -> bytes:
    value = os.getenv("SECRET_KEY", "").strip()
    if not value:
        raise OTPConfigurationError("SECRET_KEY is required for OTP protection.")
    return value.encode("utf-8")


def _otp_digest(email: str, otp: str) -> bytes:
    message = f"{email}:{otp}".encode("utf-8")
    return hmac.new(_secret(), message, hashlib.sha256).digest()


def _smtp_settings() -> tuple[str, str, str, int, bool]:
    username = os.getenv("EMAIL_USER", "").strip()
    app_password = os.getenv("EMAIL_APP_PASSWORD", "").strip()
    if not username or not app_password:
        raise OTPConfigurationError(
            "EMAIL_USER and EMAIL_APP_PASSWORD must be configured."
        )

    try:
        port = int(os.getenv("SMTP_PORT", "465"))
    except ValueError as exc:
        raise OTPConfigurationError("SMTP_PORT must be an integer.") from exc
    if port not in {465, 587}:
        raise OTPConfigurationError("SMTP_PORT must be 465 or 587.")
    return (
        os.getenv("SMTP_HOST", "smtp.gmail.com").strip(),
        username,
        app_password,
        port,
        port == 465,
    )


def _email_message(email: str, otp: str) -> EmailMessage:
    safe_otp = escape(otp)
    message = EmailMessage()
    message["Subject"] = "Your Resume Atlas verification code"
    message["From"] = os.getenv("EMAIL_FROM", os.getenv("EMAIL_USER", ""))
    message["To"] = email
    message.set_content(
        f"Your Resume Atlas verification code is {otp}. It expires in 5 minutes."
    )
    message.add_alternative(
        f"""<!doctype html>
<html lang="en">
  <body style="margin:0;background:#f3f6f4;color:#16231f;font-family:Arial,Helvetica,sans-serif;">
    <div style="max-width:560px;margin:32px auto;padding:0 16px;">
      <div style="background:#173d34;border-radius:12px 12px 0 0;padding:24px 28px;color:#ffffff;">
        <div style="font-size:12px;letter-spacing:2px;text-transform:uppercase;opacity:.8;">Resume Atlas</div>
        <h1 style="margin:10px 0 0;font-size:26px;line-height:1.2;">Verify your email</h1>
      </div>
      <div style="background:#ffffff;border:1px solid #dce5e0;border-top:0;border-radius:0 0 12px 12px;padding:28px;">
        <p style="margin:0 0 18px;font-size:16px;line-height:1.6;">Use this one-time code to continue securely:</p>
        <div style="background:#eef5f1;border:1px solid #c9ded3;border-radius:8px;padding:18px;text-align:center;">
          <strong style="font-size:34px;letter-spacing:8px;color:#173d34;">{safe_otp}</strong>
        </div>
        <p style="margin:20px 0 0;color:#53635d;font-size:13px;line-height:1.5;">This code expires in 5 minutes and can be tried up to 3 times. If you did not request it, you can safely ignore this email.</p>
      </div>
    </div>
  </body>
</html>""",
        subtype="html",
    )
    return message


def _send_email(message: EmailMessage, host: str, username: str, password: str, port: int, ssl_mode: bool) -> None:
    try:
        if ssl_mode:
            with smtplib.SMTP_SSL(host, port, context=ssl.create_default_context(), timeout=20) as smtp:
                smtp.login(username, password)
                smtp.send_message(message)
        else:
            with smtplib.SMTP(host, port, timeout=20) as smtp:
                smtp.ehlo()
                smtp.starttls(context=ssl.create_default_context())
                smtp.ehlo()
                smtp.login(username, password)
                smtp.send_message(message)
    except (OSError, smtplib.SMTPException) as exc:
        raise OTPDeliveryError("The verification email could not be sent.") from exc


def send_otp(email: str) -> None:
    """Generate and email an OTP, retaining only its protected digest."""
    normalized_email = _normalize_email(email)
    now = time.time()
    cooldown = int(os.getenv("OTP_SEND_COOLDOWN_SECONDS", str(DEFAULT_SEND_COOLDOWN_SECONDS)))
    with _records_lock:
        previous = _records.get(normalized_email)
        if previous and now - previous.last_sent_at < cooldown:
            raise OTPRateLimitError("Please wait before requesting another code.")

    host, username, password, port, ssl_mode = _smtp_settings()
    otp = f"{secrets.randbelow(1_000_000):06d}"
    _send_email(_email_message(normalized_email, otp), host, username, password, port, ssl_mode)
    with _records_lock:
        _records[normalized_email] = _OTPRecord(
            digest=_otp_digest(normalized_email, otp),
            expires_at=now + OTP_TTL_SECONDS,
            last_sent_at=now,
        )


def verify_otp(email: str, user_submitted_otp: str) -> bool:
    """Verify an OTP once, consuming it after success, expiry, or lockout."""
    normalized_email = _normalize_email(email)
    submitted = str(user_submitted_otp or "").strip()
    if not re.fullmatch(r"\d{6}", submitted):
        return False

    now = time.time()
    with _records_lock:
        record = _records.get(normalized_email)
        if record is None:
            return False
        if now >= record.expires_at or record.attempts >= MAX_ATTEMPTS:
            _records.pop(normalized_email, None)
            return False
        record.attempts += 1
        matches = hmac.compare_digest(record.digest, _otp_digest(normalized_email, submitted))
        if matches:
            _records.pop(normalized_email, None)
            return True
        if record.attempts >= MAX_ATTEMPTS:
            _records.pop(normalized_email, None)
        return False


def clear_expired_otps() -> int:
    """Remove expired records and return the number removed."""
    now = time.time()
    with _records_lock:
        expired = [email for email, record in _records.items() if now >= record.expires_at]
        for email in expired:
            _records.pop(email, None)
    return len(expired)